# Generated by Django 5.0 on 2024-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_body_article_created_time_article_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_time',
        ),
    ]
